### ISSUE TITLE
Need help to generate output in different format

### ISSUE THREAD

**Issue by asksonu** [mewwts/addict#108]
Hi, I am looking to generate json in the similar format (tree like) from original file. But I have two changes in the output. 
1. Every node should also give details like name of column, name of the attribute 
2. Get percentages of records (instead of count) under each category

Attached screenshot of the expected output. 
Help would be really appreciated. 

![screenshot](https://user-images.githubusercontent.com/36418425/52044512-61d9c900-2568-11e9-9e27-4b164b2ac88d.PNG)

**Comment by mewwts** [comment]
Hey @asksonu 

Thanks for reaching out! Are you sure this is an issue with `addict`?

**Comment by asksonu** [comment]
Hi @mewwts

No, I was wondering if package 'addict' can be used to generate json output in the format specified.

**Comment by mewwts** [comment]
Well, you certainly can create dicts that contain information like the above with `addict`, but I'm not sure you need it. However, depending on what your data looks like perhaps this section on counting could be interesting to you: https://github.com/mewwts/addict#counting?
