### ISSUE TITLE
Raise an error on accessing a property that does not exist

### ISSUE THREAD

**Issue by amandlek** [mewwts/addict#109]
I've been very happy using addict so far, but I recently ran into a pretty dangerous bug due to a spelling error in one of my properties where I expected the addict object to have a boolean value for a key, but it instead returned an empty dictionary (since the key was never created). 

To be more concrete, I had a check that looked like `if dict.a.b.c:` but the `c` key was never created, since I had a spelling mistake. It would be nice if a missing attribute error could be thrown in this case, but I'm not sure if that would prevent some other functionality of addict (just as chaining attributes together to define all of them at once, as in `dict.a.b.c.d = 1`). Could you please let me know if something like this might be possible? 

Also, if it matters, I am using addict version 2.1.3, due to some change that broke objects I had that were inheriting from Addict dictionaries. Thanks!

**Comment by mewwts** [comment]
Hey @amandlek,

Thanks for reaching out. This is indeed dangerous, but you're completely right, changing this would disable the nested setting of attributes and thus deem `addict` completely useless!

Thanks for reporting breaking inheritance - you're not the first and I will address it in an upcoming release.

Thanks again!
