### ISSUE TITLE
Segmentation fault, when using with numpy and itertools

### ISSUE THREAD

**Issue by c0ntradicti0n** [mewwts/addict#111]
I tried that... I don't know, if it's a nice idea, but with normal dicts, that works fine.

```
import addict
b = addict.Dict({'t':{'o':2}})
import numpy
numpy.array([b,b,b,b])
```

I get: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by jwilk** [comment]
I've narrowed your example down to this Numpy bug: https://github.com/numpy/numpy/pull/13273

But what do you mean by "and itertools"?

**Comment by c0ntradicti0n** [comment]
Ah, pretty well. 

We could edit the thread, the occurence of itertools is a rudiment, from a previous version of this issue. Sorry, my fault.

**Comment by mewwts** [comment]
Hey guys, did https://github.com/numpy/numpy/pull/13273 fix this for you?

**Comment by mewwts** [comment]
Closing due to staleness.
