### ISSUE TITLE
Accessor for potentially missing field

### ISSUE THREAD

**Issue by hawkins** [mewwts/addict#114]
I'm looking to use this library for both setting and getting attributes from a large dictionary.

Setting chained things works beautifully:

```python
data['field']['name']['leaf'] = 'set'
```

But, if I wanted to access a field that may not exist, I get back an empty dictionary, where I would expect to instead receive a `None` to represent that there is no value present in the field, rather than there is an empty dictionary at the field:

```python
value = data['some']['missing']['field']
# value is `{}`
# value should be `None` instead
```

---

I recognize that this behavior to fill an empty dictionary in case we need to assign to it makes sense for most use cases, and is fundamental to the module. However, would it be possible to implement an accessor function which does not fill missing in the root node?

I.e.,

```python
# This core functionality would be unchanged
value = data['some']['missing']['field'] # still `{}`

# But we could add a new accessor function:
value = addict.get(data['some']['missing']['field']) # `None`
# or...
value = addict.get(data, 'some', 'missing', 'field')
# maybe even as `dict.get`, though that would be dangerous for dicts with `get` as a key, so I don't like this as much:
value = data.get('some', 'missing', 'field')
```

One such implementation I can think in my head (although naive and inefficient) can be done by simply trying to access the value and, if a key error occurs, return None instead of raising. Otherwise, return the found value:

```python
# addict.get
def get(d, *keys):
    plain = d.to_dict() # Just so we get KeyError, though this is far too expensive for a lookup - naive
    try:
        for key in keys:
            plain = plain[key]
        return plain
    except KeyError:
        return None
```

Is there a better way to do this that could leverage addict's internals to avoid an expensive call to `to_dict`?

**Comment by mewwts** [comment]
Hey @hawkins,

One thing that pops to mind is using the `in` operator, by asking for inclusion of the last key in the nested dict
```Python
>>> 'field' in data.some.missing
False
```
If `some` or `missing` or `field` is not in the path, it will return `False`.

Does this help?

**Comment by hawkins** [comment]
Very good point, that's a great way to leverage the defaulting of addict. Something like this might cut it then:

```python
def get(di, *keys):
    d = di
    for key in keys[0:-1]:
        d = d[key]
    
    if keys[-1] in d:
        return d[keys[-1]]
    else
        return None
```

That solves my problem, thanks! But I wonder - do you see any value in adding such a get function to the library itself, or would you rather leave it out and leave its implementation up to users?

**Comment by mewwts** [comment]
I'm leaning towards keeping addict lean and understandable (not always easy :sweat_smile:),

Out of curiosity, what is the purpose (or benefit) of having a function return `None` instead of checking the boolean output of `in`?

**Comment by hawkins** [comment]
Understandable!

It’s for the semantics of it: “get the value”, and when there is no value, the value is said to be none.

I’m using this in cases where many nested fields are optional and the final object we need to send will strip out null-like types before we send it to another system. We read some file and queries into an addict Dict.

So, with this implementation of `get` we can iterate over all the fields we are looking for and use this one call to  populate the field in our object with the addict Dict’s value or None so our system strips it out in transit. This is such a common pattern in the code that we would much prefer `payload[‘maybe’] = addict.get(a.b.c.d)` than `payload[‘maybe’] = a.b.c.d if d in a.b.c else None`.

But I’m happy now, and since we’re not going to add this in I’m closing this issue. Thanks for your help and catching my oversight to make this check a lot faster! 🙌😁

**Comment by mewwts** [comment]
I see. There is the case for making a _utils_ module where we can abstract common patterns into. This is certainly a candidate for that.

Thanks so much for your contribution. :+1:
