### ISSUE TITLE
Dict adds quote when retrieving str values

### ISSUE THREAD

**Issue by hl037** [mewwts/addict#124]
When retrieving string values to a `Dict`, quote are added around the string...

```
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from addict import Dict
>>> d = Dict()
>>> d.a = "TEST"
>>> repr(d.a)
"'TEST'"
```

...I tried did it on a venv to be sure no other module conflict since this bug since qui improbable...

**Comment by mewwts** [comment]
Glad you figured it out!
