### ISSUE TITLE
Dict() inconsistent with dict() initialization

### ISSUE THREAD

**Issue by jobh** [mewwts/addict#125]
I noticed this when trying to use with xmldict (https://github.com/martinblech/xmltodict). Sometimes a plain value becomes a list, with the first element an empty dict and the value in the second element:

```
>>> xml = "<root><x>1</x></root>"
>>> xmltodict.parse(xml, dict_constructor=dict)
{'root': {'x': '1'}}
>>> xmltodict.parse(xml, dict_constructor=addict.Dict)
{'root': [{}, {'x': [{}, '1']}]}
```

I don't know how xmltodict calls the constructor, but there is obviously something that is not processed in the same way.

**Comment by jobh** [comment]
After some digging, it looks like it is caused by the `__missing__` method returning `Dict()` when key is not found.

I see, this is to enable stuff like
```
body = Dict()
body.query.filtered.query.match.description = 'addictive'
```
but there should be a caveat in the documentation. Or maybe opt-in functionality (`Dict` and `DefaultDict` classes for example).

**Comment by mewwts** [comment]
Yeah, that doesn't look right!
One thing you could do is is `Dict(xmltodict.parse(xml, dict_constructor=dict))`, however feel free to PR some lines into the README.

**Comment by jobh** [comment]
See also https://github.com/martinblech/xmltodict/pull/256, to fix the other end

**Comment by mewwts** [comment]
Thanks!
