### ISSUE TITLE
Adding support for merge operator `|` and `|=` (as python 3.9 dict merge)

### ISSUE THREAD

**Issue by hl037** [mewwts/addict#127]
Python 3.9's dicts support merging using the `|` and the '|=' operator.

Adding it to addict would : 

1) Increase dict compatibility

2) Provide dict alternative with support of this operator for previous python versions

It could be implemented using the snippet the PEP  provide as implementation example for dicts

References : 
https://docs.python.org/3.9/whatsnew/3.9.html#dictionary-merge-update-operators
https://www.python.org/dev/peps/pep-0584/#reference-implementation

**Comment by mewwts** [comment]
Thanks!
