### ISSUE TITLE
Arrays in dictionaries, how to denote

### ISSUE THREAD

**Issue by psmgeelen** [mewwts/addict#140]
Hi there,
So I am trying to fill arrays, within dictionaries on the fly as follows:
```root.targets[0].table = 'alerts'```

Which gives me the result:
```>>> {'targets': {'0': {'table': 'alerts}}}```

Where I wanted to have:
```>>> {'targets': [{'table': 'alerts}]}```

Naturally I have more position in the list that need to be filled as well. What am I doing wrong here?

Reproducible example:
```
from addict import Dict
root = Dict()
root.targets[0].table = 'alerts'
print(root.to_dict()) 
```

Thanks for your time!

**Comment by krema** [comment]
```
list(root.targets.values())
```
