### ISSUE TITLE
base on OrderedDict?

### ISSUE THREAD

**Issue by renzhn** [mewwts/addict#42]
OrderedDict is another dict library inherits to python's dict.
why not base on it ?

**Comment by mewwts** [comment]
I simply had no need for ordered keys when I made it.

**Comment by renzhn** [comment]
an `OrderedAddict` maybe ?

**Comment by mewwts** [comment]
It's not unthinkable, but as of now I won't go ahead and implement this.

**Comment by renzhn** [comment]
I'm using list in a dict as an alternative and it's working.

**Comment by mewwts** [comment]
Good.

**Comment by mewwts** [comment]
Hey @renzhn, 3.6 will get insertion order on keys: https://mail.python.org/pipermail/python-dev/2016-September/146327.html

**Comment by renzhn** [comment]
That's great! Nice to hear that!
