### ISSUE TITLE
IPython autocomplete on Dict keys?

### ISSUE THREAD

**Issue by Who8MyLunch** [mewwts/addict#45]
I love the whole concept behind this package!  Thanks for making it real.

I spend a lot of time in IPython looking at data and prototyping pieces of my projects.  In that environment it is very natural to hit tab and expect autocomplete to show a nice list of available attributes.

The sad part is this doesn't work for the keys of addict's Dicts.  This was also noted in another Issue topic:  #26 .  I don't really know the mechanics of how IPython's autocomplete does its thing.  Easy or complicated? I might look into that just to satisfy my curiosity.

**Comment by sabhiram** [comment]
If I am not mistaken, it will do so by essentially querying `dir(object)`.

See here: http://ipython.org/ipython-doc/dev/config/integrating.html
https://docs.python.org/2/library/functions.html#dir

**Comment by mewwts** [comment]
Hi @Who8MyLunch, thanks for reaching out, I'm glad you like the package! I will take a look at this, if you don't beat me to it, as I'm away this weekend! :+1:

**Comment by sabhiram** [comment]
We currently just return the `dir(Dict)` - Do you see "any" options as far as the autocomplete in ipy? My guess is you see some of the "Dict" methods.

**Comment by mewwts** [comment]
Closing this, as it was fixed by #46.
