### ISSUE TITLE
Try to make a list inside dict

### ISSUE THREAD

**Issue by gabriel-tessier** [mewwts/addict#53]
Hi,

I'm maybe didn't use the declaration correctly but I try to make something like:
my_query = Dict()
my_query.query.filtered.filter.bool['must'].bool['should'] = [{'term': {'id': 'foo'}....
this generate the following syntax :
`{'query': {'filtered': {'filter': {'bool': {'must': {'bool':...`
and not `{'query': {'filtered': {'filter': {'bool': {'must': [{'bool':...`
as I expected. 

What is the good way to perform this?

Thanks for any help!

**Comment by mewwts** [comment]
Hey @gabriel-tessier!
I must be honest here and say that I'm not entirely sure what you're trying to achieve.
If you want to put a list inside the addict I'd just do:
```Python
my_query.query.filtered.filter.bool['must'] = [1, 2, 3] # Or any other list
```
If you want to put a list inside `.bool.must` and another one in `.bool.should` you should do that on two lines:
```Python
my_query.query.filtered.filter.bool.must = [1, 2, 3]
my_query.query.filtered.filter.bool.should = [4, 5, 6]
```

The `['must']`-syntax achieves the same thing as `.must`, brackets (`[]`) indicate item access, while the dot-notation (`.`) indicates attribute access.  Both try to access or set the same elements in addict.

**Comment by gabriel-tessier** [comment]
Thanks to take time to reply!
What I want to do is something like (shorter than the real one):
{"query":
  {"bool":
    {"must": [
       {"term": {"id":1},
       {"bool": 
          {"should":[
            {"term":{"foo":"bar"},
            {"term":{"foo":"barb"}
]}}]}}}

If I write this : 
1. query.bool.['must'].bool.['should'] = [{"term":{"foo":"bar"},{"term":{"foo":"barb"}]
I have the same result that if I write it like that :
2. query.bool.must.bool.['should'] = [{"term":{"foo":"bar"},{"term":{"foo":"barb"}]

But I expect to have a list in must not a dict, cause I write "query.bool.['must']" not "query.bool.must"
Hope this one is more understandable, sorry for the confusion!

**Comment by mewwts** [comment]
You can only put a letter behind a `.` in Python. So `query.bool.['must']` is invalid syntax.

**Comment by gabriel-tessier** [comment]
I update my comment.
I just write the code for the example, didn't check the validity.
