### ISSUE TITLE
For iPython an addition key '_ipython_canary_method_should_not_exist_' is added.

### ISSUE THREAD

**Issue by chuanconggao** [mewwts/addict#73]
Under iPython (Python 2.7 & addict 1.1.0), if we have the following code:
```python
from addict import Dict
d = Dict()
print(d.keys())
```
We get the following output:
```
['_ipython_canary_method_should_not_exist_']
```

**Comment by mewwts** [comment]
Hi @chuanconggao - thanks for reporting this.

I've had some issues with Jupyter / IPython before - I'm not entirely sure how to deal with them. [Here](https://github.com/ipython/ipython/blob/41bc8e5ec492820b32f60122dd178300f7e01240/IPython/utils/dir2.py#L65)'s the piece of code in IPython that causes the behavior above. And in #26 you can see an earlier discussion.
