### ISSUE TITLE
test_copy(self) is wrong?

### ISSUE THREAD

**Issue by klahnakoski** [mewwts/addict#77]
`test_copy` appears to be a copy of the deep copy test, and not correct

        a = Dict()
        a.child.immutable = 42
        a.child.mutable = foo

        b = a.copy()

        # immutable object should not change
        b.child.immutable = 21
        self.assertEqual(a.child.immutable, 42)

the last line should read 

        self.assertEqual(a.child.immutable, 21)

The `copy()` should be a shallow copy with `b.child` pointing to the same object as `a.child`, so have been changed to 21.

**Comment by mewwts** [comment]
Hi @klahnakoski - thanks for reporting this.
You're right - the behaviour you describe with be inline with Python's `dict`.  We should reimplement `__copy__` to not use the constructor, which will clone dict-like objects.

**Comment by mewwts** [comment]
Hi @klahnakoski, does #78 look better to you?

**Comment by klahnakoski** [comment]
Yes, the test looks good to me. Thank you.

You may consider removing the `Dict.copy()` method completely, deferring to `dict.copy()` instead.

**Comment by mewwts** [comment]
That won't work, the new instance will be a `dict`.

Thanks again for spotting this! 👍
