### ISSUE TITLE
Add functionality to flat entries

### ISSUE THREAD

**Issue by delijati** [mewwts/addict#80]
It would be helpful to flat entries like:

```python
>>> foo = {'foo': {'bar': 'baz', 'qux': 'corge'}}
>>> # to
>>> foo
{'foo:bar': 'baz', 'foo:qux': 'corge'}
```

To save complex structures in a simple key value store.

**Comment by mewwts** [comment]
That's interesting, and I see the value of it. However in my mind that is not something we should have in `addict`, as this is just as useful for normal dictionaries. 

Thanks @delijati 👍
