### ISSUE TITLE
hasattr behaviour

### ISSUE THREAD

**Issue by Thomasillo** [mewwts/addict#81]
Hi, I encountered this, when writing an extension to addict.Dict..
I don't think this behaviour is what would be expected..

    In [1]: import addict
    
    In [2]: addict.__version__
    Out[2]: '2.0.0'

    In [3]: d = addict.Dict()

    In [4]: hasattr(d, 'this_should_not_exist')
    Out[4]: True

**Comment by mewwts** [comment]
Hey, 

This is unavoidable since `hasattr` is implemented using `getattr`. See https://docs.python.org/3/library/functions.html#hasattr. A pattern that would work would be
```
d = addict.Dict()
if d['this_key_is_not_presnet']:
    print('this doesn't actually happen')
```

**Comment by Thomasillo** [comment]
Hi, thanks for your answer!

Maybe it would make sense to alter the behaviour when peeking into non-(yet-)existent attributes.

In practice, the behaviour above is --in my opinion-- highly unintuitive and has in my practice led to a number of bugs (some hard to find). Of course one could use the `d['xy']` Syntax but using addict in the first place was to avoid that.
In one other case I'm checking the values in a Dict which can be Dicts as well for an atribute. It's not possible to use the `d['xy']` syntax here because values might or might not have the `__getitem__` method. So here you have to check for being a dict first and then use `d['xy']`. Appears clumsy to me ;) 
However peeking on nonenxistent attributes could yield an AttributeError without much trouble (I think).. And setting attributes should be unaffected by that.

Please let me know if this makes sense.. Thank you!!

**Comment by mewwts** [comment]
Hi!

`addict` does not differentiate between attributes and and items (except when it comes to attributes that belong to a superclass such as `dict`, those can not be set again). That means that the example above is valid in the following form as well;

```Python
d = addict.Dict()
if d.this_key_is_not_present:
    print('this doesn't actually happen')
```

In fact, I don't think it's possible to implement the nested setting of attributes, i.e.
```Python
d = addict.Dict()
d.a.b.c = 2
```
without returning a `addict.Dict` instance on a `__getattr__` call. I encourage you to take a look at the source in, but I'm of course also open to be proven wrong!

Hope you have a great weekend, and thanks for contributing to `addict`.

**Comment by mewwts** [comment]
Closing this for now. :)

**Comment by benjhastings** [comment]
So I know this is pretty old but I'm just adding my two cents to this.  I came across this issue when I overrode `__missing__` as specified in the docs [here](https://github.com/mewwts/addict#default-values).  Doing this meant that a call to `hasattr` would fail with a `KeyError: '<missing attribute>'` as `hasattr` catches `AttributeError`.

I resolved this by doing the following:

```
from addict import Dict

class MyAddictSubclass(Dict):
    def __getattr__(self, item):
        try:
            super(MyAddictSubclass, self).__getattr__(item)
        except KeyError:
            raise AttributeError("%r object has no attribute %r" %
                                 (self.__class__.__name__, item))

    def __missing__(self, key):
        raise KeyError(key)
```
