### ISSUE TITLE
Handle setdefault on proxy dicts

### ISSUE THREAD

**Issue by bmerry** [mewwts/addict#83]
With 2.0.0, the following pattern I was using is broken:
```python
command.environment.setdefault('variables', []).append(value)
```
The idea here is that `command['environment']['variables']` is a list of dicts, but any part of that path might or might not exist. In 1.x, the `command.environment` would actually insert a `environment` key into `command`. In 2.0.0, the `environment` dict is created but not inserted into the parent, because there is no `setitem`.

Proposal: all mutating member functions of `Dict` (specifically including `setdefault`) should insert into the parent.

**Comment by mewwts** [comment]
Hey @bmerry, thanks for reporting this. 

This is interesting, I've never actually used `setdefault`, and I tried reading up on the [implementation in CPython](https://github.com/python/cpython/blob/1b8df107f867fb05ff39ebee7c55f0a907e7ad5f/Objects/dictobject.c). Anyways, I ended up implementing something in #84 which I think works. Please have a look.

**Comment by mewwts** [comment]
Thank you again @bmerry. 👍
