### ISSUE TITLE
Link to parent causes reference cycles

### ISSUE THREAD

**Issue by bmerry** [mewwts/addict#86]
With addict 2.0.0, this code generates a reference cycle and may lead to memory leaks:
```
from addict import *
a = Dict()
a.x.y = 1
```
Here `a` contains a reference to `a.x`, and `a.x.__parent__` points back to `a`, thus creating a cycle.

`__setitem__` should probably clear `__parent` and `__key` after they've served their purpose.

**Comment by mewwts** [comment]
Thanks @bmerry. I've release 2.0.1 with the most of the fixes you've pointed out. I want to encourage you do a review of #84, and submit a PR in the future. You've already helped make `addict` a lot better.
