### ISSUE TITLE
Document that update works differently to normally dictionary

### ISSUE THREAD

**Issue by bmerry** [mewwts/addict#87]
Looking at the source of addict, I noticed that the `update` method helpfully recurses into nested dictionary to do the update. That isn't documented though, and could be a surprise since it's inconsistent with the base `dict` class. For example:
```python
>>> d = {'a': {'b': 3}}
>>> d.update({'a': {'c': 4}})
>>> print(d)
{'a': {'c': 4}}
>>> D = Dict({'a': {'b': 3}})
>>> D.update({'a': {'c': 4}})
>>> print(D)
{'a': {'b': 3, 'c': 4}}
```

**Comment by mewwts** [comment]
Thanks @bmerry. Will add it to the documentation. 👍
