### ISSUE TITLE
`self` can't be used as a key

### ISSUE THREAD

**Issue by grundic** [mewwts/addict#93]
```python
Dict(self='this')
>>> TypeError: __init__() got multiple values for keyword argument 'self'
```

That's because __init__ method is present and has `self` parameter.

There are several ways to overcome this issue:
1. rename `self` parameter in __init__ method to some unique string/guid. Here how it could look like:
```python
    def __init__(_8629116b_4d94_42d9_bee1_d8374f6938a7_, *args, **kwargs):
        object.__setattr__(_8629116b_4d94_42d9_bee1_d8374f6938a7_, '__parent', kwargs.pop('__parent', None))
        object.__setattr__(_8629116b_4d94_42d9_bee1_d8374f6938a7_, '__key', kwargs.pop('__key', None))
        for arg in args:
            if not arg:
                continue
            elif isinstance(arg, dict):
                for key, val in arg.items():
                    _8629116b_4d94_42d9_bee1_d8374f6938a7_[key] = _8629116b_4d94_42d9_bee1_d8374f6938a7_._hook(val)
            elif isinstance(arg, tuple) and (not isinstance(arg[0], tuple)):
                _8629116b_4d94_42d9_bee1_d8374f6938a7_[arg[0]] = _8629116b_4d94_42d9_bee1_d8374f6938a7_._hook(arg[1])
            else:
                for key, val in iter(arg):
                    _8629116b_4d94_42d9_bee1_d8374f6938a7_[key] = _8629116b_4d94_42d9_bee1_d8374f6938a7_._hook(val)

        for key, val in kwargs.items():
            _8629116b_4d94_42d9_bee1_d8374f6938a7_[key] = _8629116b_4d94_42d9_bee1_d8374f6938a7_._hook(val)
```
Though, it's still impossible to use key with `_8629116b_4d94_42d9_bee1_d8374f6938a7_` name :)
2. create factory method, which will protect field names and the unprotect them. Here is an [example](https://github.com/prawn-cake/simple-models/commit/3e37cc29870724fc829db7a270bde1d62eb2c3af#diff-a25c572eb55240a5edfd9d31c43ab3dbR223).

Not sure whether you are interested in fixing it, but I thought you would be interested in it.

**Comment by mewwts** [comment]
There's actually two other field names which are _problematic_; `__parent` and `__key` which are used other places in the code. For now I think doing `__self` instead of `self` should limit the impact of this?

**Comment by grundic** [comment]
Hi @mewwts,
Yep, `__self ` should be less possible option for some JSON API, where `self` is actually [part](http://jsonapi.org/) of it :)

**Comment by mewwts** [comment]
Right, thanks. In any case keep in mind that you can use `self` as a key, just not as a `kwarg`.
